### ISSUE TITLE
Example code & detection of errors? 

### ISSUE THREAD

**Issue by cyberchucktx** [mschout/perl-GnuPG-Interface#1]
Are there other sources of information on this module/package? Listserv or forum? 

I'd like to contribute: 
1) Simple(r) sample code showing encryption and decryption (file-based).
2) Information on how to detect errors when using this package. 

On #2: the short answer is to check the PERL global variable $? after execution (after the "waitpid" command). If nonzero then there was an error and the ERROR and STATUS handles can be used to get more information. 

So ... any idea where i can post my examples including status checking?

**Comment by mschout** [comment]
This is not the official repo for GnuPG::Interface.  This is merely a "git cpan clone" of the module that I used to apply a fix and I use this as a submodule in a "darkpan" repository.    I filed my changes upstream at https://rt.cpan.org/Ticket/Display.html?id=105269 but the author never responded.

You should reach out to the author of the module, who is jesse@cpan.org according to the POD docs.

This module has several COMAINTs in PAUSE though, so you might copy al of them:

ALEXMV@cpan.org, BPS@cpan.org, FTOBIN@cpan.org, Jesse@cpan.org, RUZ@cpan.org

or, make a patch and file it at bug-gnupg-interface@rt.cpan.org.  However, given the number of outstanding tickets on this module I'm not sure that will help.

Sorry!

**Comment by cyberchucktx** [comment]
Interesting. There apparently ISN'T a GITHUB repository for this anymore (that I can find, anyway). I'll EMAIL the authors, thanks for the response.
